# -*- coding: utf-8 -*-

"""
function_templates
~~~~~~~~~~~~~~~~~~~

Jinja2 templates for the autogenerated functions
"""

standard_function = (
    'def {{ name }}(me, method: str, extra_params={}) -> dict:\n'
    '    return request(me, method, "{{ url }}", extra_params=extra_params)\n'
    '\n\n\n'
    )

parameter_function = (
    'def {{ name }}(me, method: str, _{{ parameter1}}=None, extra_params={}) -> dict:\n'
    '    parameter1 = {"{{ parameter1 }}": _{{ parameter1 }}} if _{{ parameter1 }} else {}\n'
    '    return request(me, method, "{{ url }}", parameter1, extra_params=extra_params)\n'
    '\n\n\n'
    )
